### ISSUE TITLE
Not working with new ProxyContract

### ISSUE THREAD

**Issue by definoob** [tornadocash/tornado-cli#11]
I get this error when I try to run this code

![image](https://user-images.githubusercontent.com/54032883/125675258-9cf5b3a9-2006-4556-9b15-59991081fcaa.png)

**Comment by definoob** [comment]
P.S. I've updated the ProxyContract address from config.js

**Comment by definoob** [comment]
After checking a little bit more, I found that ERC20Torando.json has got Deposit/Withdrawal events while Proxy doesn't have got it. 
Is there any solution for this?

**Comment by 0xZick** [comment]
> I get this error when I try to run this code
> 
> ![image](https://user-images.githubusercontent.com/54032883/125675258-9cf5b3a9-2006-4556-9b15-59991081fcaa.png)

I made a PR that fixes this, you can try to make a deposit through the fixTornado branch or wait for the merge in the master
