### ISSUE TITLE
`compliance` doesn't work

### ISSUE THREAD

**Issue by paulmillr** [tornadocash/tornado-cli#13]
Also it makes request to etherscan, which is not cool. I think a confirmation popup should be presented before the request.

**Comment by sambacha** [comment]
this *should* be fixed, but I don't use tornado cash so I can not confirm: https://github.com/tornadocash/tornado-cli/commit/c3653bf6e4232fb73126b332b70810a570e564e3

**Comment by 0xAyanami** [comment]
Fixed & Tested from https://github.com/tornadocash/tornado-cli/pull/16
