### ISSUE TITLE
Feature request: Send transaction when gas is lower then

### ISSUE THREAD

**Issue by DonnyPerni** [tornadocash/tornado-cli#6]
One of the main problem for adoption of tornado cash is the gas cost that with the recent congestion of the Ethereum network is getting really high, I think a good feature to add would be to add a function that continuously check if the gas price is under a certain value (set by the user) and when it is, it send the proof for the withdraw to the relayer.

It can be added as parameter to the executable, something like: ` --gasunder <gas>`

As bonus to this you get that you have a withdraw at a random time, so if someone try to analyze the time of withdraw and send to to understand the timezone where the transactions came from it would be useless.

**Comment by 0xAyanami** [comment]
EIP-1559 transaction submission is now patched here https://github.com/tornadocash/tornado-cli/pull/16, this will reduce the transaction fees.
